### ISSUE TITLE
Makefile editing is broken

### ISSUE THREAD

**Issue by waddlesplash** [olta/pe#11]
1. Create a new Makefile (Tracker -> New -> Makefile)
2. Open it with Pe, select Sources, and select some files

Two problems:
  - It tries to "save as" (how did it forget the file name?)
  - If you "save as", it does not add the files that were added

**Comment by TwoFX** [comment]
A quick analysis shows that the problem essentially boils down to the wrong code path being taken [here](https://github.com/olta/pe/blob/bf9fb9f3e9bfa7ee486aeae0fb5e9750d9377e0d/Sources/CDoc.cpp#L142); to be more precise EntryRef() returns `NULL` although it really should not. This small snippet from a Pe UML class diagram shows the issue:
![image](https://cloud.githubusercontent.com/assets/2065352/5601273/fe4a8cb6-92f5-11e4-9b70-819770cfc4c6.png)
The entry_ref for the file is stored in a CDocIO which is owned by a CDoc. However, as you can see, the UML diagram is cyclic! There are two ways to get to CDoc: The PProjectWindow aready is a CDoc itself, but it also has fPrjFile, which is also a CDoc.
When PProjectWindow is initialized, the entry_ref successfully makes its way up the inheritance way, so that CDoc is correctly initialized. The CProjectFile is created by CProjectRoster::ParseProjectFile, which is essentially a factory method. In this method the entry_ref is essentially lost, the entry_ref on fDocIO never gets set. Now, when it is time to save, [fPrjFile->Save() gets called](https://github.com/olta/pe/blob/bf9fb9f3e9bfa7ee486aeae0fb5e9750d9377e0d/Sources/PProjectWindow.cpp#L276), which results in the wrong branch being taken since CDoc::Save thinks that there is no entry_ref associated with the project.
A solution is to not override Save() in PProjectWindow, but rather fall back on CDoc::Save(), which calls GetText(BString &). Right now, PProjectWIndow does nothing in that method (PProjectWindow is not really a CDoc, because it refuses to implement GetText. CProjectFile is not really a CDoc, because it refuses to deal with the entry_ref. Bad class design?). Change that to a call to fPrjFile->GetText() to connect the two. This change should fix the saving problem.

**Comment by olta** [comment]
Again, good analysis - the class design is indeed questionable (which I'm afraid is my fault).
